feat: installation of the Sumo monitors as part of setup process (#2250)
* feat: installation of the Sumo monitors as part of setup process

* feat: configurable e-mail notifications for monitors

* feat: do not run shellcheck on monitors.sh

* feat: fixed Markdown formatting

* feat: adjust tests after rebase

* feat: changelog

* feat: shellcheck for generated monitors.sh

* feat: rename `sumologic.setup.monitors.monitoringDisabled` to `sumologic.setup.monitors.disabled`

* feat: new line at th end of monitors.sh

* feat: link to monitors in NOTES when installation is disabled

* feat: style improvements

* feat: rename monitors.setupEnabled -> monitors.enabled

* feat: rename monitors.disabled -> monitors.monitorStatus

* Empty lines before EOF

Co-authored-by: Dominik Rosiek <58699848+sumo-drosiek@users.noreply.github.com>

Co-authored-by: Dominik Rosiek <58699848+sumo-drosiek@users.noreply.github.com>

diff --git a/tests/helm/terraform/static/all_fields.output.yaml b/tests/helm/terraform/static/all_fields.output.yaml
--- a/tests/helm/terraform/static/all_fields.output.yaml
+++ b/tests/helm/terraform/static/all_fields.output.yaml
@@ -145,6 +145,61 @@ data:
         }
       }
     }
+  monitors.sh: |
+    #!/bin/bash
+  
+    SUMOLOGIC_ACCESSID=${SUMOLOGIC_ACCESSID:=""}
+    readonly SUMOLOGIC_ACCESSID
+    SUMOLOGIC_ACCESSKEY=${SUMOLOGIC_ACCESSKEY:=""}
+    readonly SUMOLOGIC_ACCESSKEY
+    SUMOLOGIC_BASE_URL=${SUMOLOGIC_BASE_URL:=""}
+    readonly SUMOLOGIC_BASE_URL
+  
+    MONITORS_FOLDER_NAME="Kubernetes"
+    MONITORS_DISABLED="false"
+  
+    # verify if the k8s monitors folder already exists
+    MONITORS_RESPONSE="$(curl -XGET -s \
+            -u "${SUMOLOGIC_ACCESSID}:${SUMOLOGIC_ACCESSKEY}" \
+            "${SUMOLOGIC_BASE_URL}"v1/monitors/search?query=type:folder%20"${MONITORS_FOLDER_NAME}" | jq '.[]' )"
+    readonly MONITORS_RESPONSE
+    MONITORS_ROOT_ID="$(curl -XGET -s \
+            -u "${SUMOLOGIC_ACCESSID}:${SUMOLOGIC_ACCESSKEY}" \
+            "${SUMOLOGIC_BASE_URL}"v1/monitors/root | jq -r '.id' )"
+    readonly MONITORS_ROOT_ID
+  
+    MONITORS_FOLDER_ID="$( echo "${MONITORS_RESPONSE}" | \
+            jq -r "select(.item.name == \"${MONITORS_FOLDER_NAME}\") | select(.item.parentId == \"${MONITORS_ROOT_ID}\") | .item.id" )"
+    readonly MONITORS_FOLDER_ID
+  
+    if [[ -z "${MONITORS_FOLDER_ID}" ]]; then
+      # go to monitors directory
+      cd /monitors || exit 2
+  
+      # Fall back to init -upgrade to prevent:
+      # Error: Inconsistent dependency lock file
+      terraform init -input=false || terraform init -input=false -upgrade
+  
+      # extract environment from SUMOLOGIC_BASE_URL
+      # see: https://help.sumologic.com/APIs/General-API-Information/Sumo-Logic-Endpoints-by-Deployment-and-Firewall-Security
+      SUMOLOGIC_ENV=$( echo "${SUMOLOGIC_BASE_URL}" | sed -E 's/https:\/\/.*(au|ca|de|eu|fed|in|jp|us2)\.sumologic\.com.*/\1/' )
+      if [[ "${SUMOLOGIC_BASE_URL}" == "${SUMOLOGIC_ENV}" ]] ; then
+        SUMOLOGIC_ENV="us1"
+      fi
+  
+      TF_LOG_PROVIDER=DEBUG terraform apply \
+          -auto-approve \
+          -var="access_id=${SUMOLOGIC_ACCESSID}" \
+          -var="access_key=${SUMOLOGIC_ACCESSKEY}" \
+          -var="environment=${SUMOLOGIC_ENV}" \
+          -var="folder=${MONITORS_FOLDER_NAME}" \
+          -var="monitors_disabled=${MONITORS_DISABLED}" \
+          || { echo "Error during applying Terraform monitors."; exit 1; }
+    else
+      echo "The monitors were already installed in ${MONITORS_FOLDER_NAME}."
+      echo "You can (re)install them manually with:"
+      echo "https://github.com/SumoLogic/terraform-sumologic-sumo-logic-monitor/tree/main/monitor_packages/kubernetes"
+    fi
   providers.tf: |-
     provider "sumologic" {}
   
@@ -425,6 +480,9 @@ data:
         -auto-approve \
         -var="create_fields=${CREATE_FIELDS}" \
         || { echo "Error during applying Terraform changes"; exit 1; }
+  
+    # Setup Sumo Logic monitors if enabled
+    bash /etc/terraform/monitors.sh
   
     # Cleanup env variables
     export SUMOLOGIC_BASE_URL=
