Update tests

diff --git a/tests/terraform/static/conditional_sources.output.yaml b/tests/terraform/static/conditional_sources.output.yaml
--- a/tests/terraform/static/conditional_sources.output.yaml
+++ b/tests/terraform/static/conditional_sources.output.yaml
@@ -39,6 +39,12 @@ data:
     #
     # shellcheck disable=SC2010
     # extract target directory names from the file names using _ as separator
+    err_report() {
+        echo "Custom script error on line $1"
+        exit 1
+    }
+    trap 'err_report $LINENO' ERR
+  
     for dir in $(ls -1 /customer-scripts | grep _ | grep -oE '^.*?_' | sed 's/_//g' | sort | uniq); do
       target="/scripts/${dir}"
       mkdir "${target}"
@@ -215,7 +221,8 @@ data:
   
     # Apply planned changes
     terraform apply -auto-approve \
-        -var="create_fields=${CREATE_FIELDS}"
+        -var="create_fields=${CREATE_FIELDS}" \
+        || { echo "Error during applying terraform changes"; exit 1; }
   
     # Cleanup env variables
     export SUMOLOGIC_BASE_URL=
