Docs refactor: teraform -> Terraform

diff --git a/tests/terraform/static/default.output.yaml b/tests/terraform/static/default.output.yaml
--- a/tests/terraform/static/default.output.yaml
+++ b/tests/terraform/static/default.output.yaml
@@ -227,7 +227,7 @@ data:
   
     # Fix URL to remove "v1" or "v1/"
     export SUMOLOGIC_BASE_URL=${SUMOLOGIC_BASE_URL%v1*}
-    # Support proxy for terraform
+    # Support proxy for Terraform
     export HTTP_PROXY=${HTTP_PROXY:=""}
     export HTTPS_PROXY=${HTTPS_PROXY:=""}
     export NO_PROXY=${NO_PROXY:=""}
@@ -303,7 +303,7 @@ data:
     # Apply planned changes
     terraform apply -auto-approve \
         -var="create_fields=${CREATE_FIELDS}" \
-        || { echo "Error during applying terraform changes"; exit 1; }
+        || { echo "Error during applying Terraform changes"; exit 1; }
   
     # Cleanup env variables
     export SUMOLOGIC_BASE_URL=
@@ -328,7 +328,7 @@ data:
     }
   
     variable "create_fields" {
-      description = "If set, terraform will attempt to create fields at Sumo Logic"
+      description = "If set, Terraform will attempt to create fields at Sumo Logic"
       type        = bool
       default     = true
     }
