chore(instrjob): add deletion hooks

diff --git a/deploy/helm/sumologic/templates/opentelemetry-operator/job-instrumentation-cr.yaml b/deploy/helm/sumologic/templates/opentelemetry-operator/job-instrumentation-cr.yaml
--- a/deploy/helm/sumologic/templates/opentelemetry-operator/job-instrumentation-cr.yaml
+++ b/deploy/helm/sumologic/templates/opentelemetry-operator/job-instrumentation-cr.yaml
@@ -11,6 +11,9 @@ metadata:
   labels:
     app: {{ template "sumologic.labels.app.opentelemetry.operator.instrumentation.job" . }}
     {{- include "sumologic.labels.common" . | nindent 4 }}
+  annotations:
+    helm.sh/hook: "post-install, post-upgrade"
+    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
 spec:
   template:
     metadata:
@@ -41,16 +44,16 @@ spec:
                 ready=true
                 break
               else
-                echo "Waiting for opentelemetry-operator-controller-manager..."
+                echo "Waiting for {{ .Release.Name }}-opentelemetry-operator"
                 sleep $sleep_interval
                 counter=$(($counter + $sleep_interval))
               fi
 
               if [[ "$counter" -gt "$max_wait" ]]
               then
-                echo "Couldn't reach opentelemetry-operator-controller-manager"
+                echo "Couldn't reach {{ .Release.Name }}-opentelemetry-operator"
                 echo "Instrumentation resources not applied!"
-                break
+                exit 1
               fi
             done
 
@@ -58,6 +61,7 @@ spec:
             then
               echo "Applying Instrumentation resources"
               kubectl apply -f /tmp/instrumentation-cr.yaml
+              exit $?
             fi
       volumes:
         - name: instrumentation-cr-configmap
diff --git a/tests/helm/opentelemetry_operator_instrumentation_cr_job/static/job.output.yaml b/tests/helm/opentelemetry_operator_instrumentation_cr_job/static/job.output.yaml
--- a/tests/helm/opentelemetry_operator_instrumentation_cr_job/static/job.output.yaml
+++ b/tests/helm/opentelemetry_operator_instrumentation_cr_job/static/job.output.yaml
@@ -9,6 +9,9 @@ metadata:
     chart: "sumologic-%CURRENT_CHART_VERSION%"
     release: "RELEASE-NAME"
     heritage: "Helm"
+  annotations:
+    helm.sh/hook: "post-install, post-upgrade"
+    helm.sh/hook-delete-policy: "before-hook-creation, hook-succeeded"
 spec:
   template:
     metadata:
@@ -39,16 +42,16 @@ spec:
                   ready=true
                   break
                 else
-                  echo "Waiting for opentelemetry-operator-controller-manager..."
+                  echo "Waiting for RELEASE-NAME-opentelemetry-operator"
                   sleep $sleep_interval
                   counter=$(($counter + $sleep_interval))
                 fi
 
                 if [[ "$counter" -gt "$max_wait" ]]
                 then
-                  echo "Couldn't reach opentelemetry-operator-controller-manager"
+                  echo "Couldn't reach RELEASE-NAME-opentelemetry-operator"
                   echo "Instrumentation resources not applied!"
-                  break
+                  exit 1
                 fi
               done
 
@@ -56,6 +59,7 @@ spec:
               then
                 echo "Applying Instrumentation resources"
                 kubectl apply -f /tmp/instrumentation-cr.yaml
+                exit $?
               fi
       volumes:
         - name: instrumentation-cr-configmap
